name: solviolin
description: "A new Flutter project."
publish_to: 'none'
version: 3.1.8+29

environment:
  sdk: ^3.5.2
  flutter: 3.24.2

dependencies:
  collection: ^1.18.0
  dio: ^5.7.0
  downloadsfolder: ^1.1.1
  excel: ^4.0.6
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mobile_scanner: ^7.0.0-beta.3
  path_provider: ^2.1.5
  retrofit: ^4.4.1
  riverpod_annotation: ^2.6.1
  syncfusion_flutter_calendar: ^27.2.5
  table_calendar: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  lint: ^2.3.0
  retrofit_generator: ^9.1.5
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/
