name: solviolin
description: "A new Flutter project."
publish_to: 'none'
version: 3.1.8+29

environment:
  sdk: ^3.5.2
  flutter: 3.24.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^0.20.1
  dio: ^4.0.4
  flutter_secure_storage: ^4.2.1
  flutter_slidable: ^0.6.0
  get: ^4.6.1
  google_fonts: ^2.3.1
  intl: ^0.19.0
  pretty_dio_logger: ^1.1.1
  qr_code_scanner: ^0.6.1
  table_calendar: ^3.0.3
  wakelock: ^0.6.1+1
  cupertino_icons: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
