name: solviolin_admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.8+10

environment:
  sdk: ^3.5.2
  flutter: 3.24.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  solviolin_common:
    path: ../solviolin_common

dev_dependencies:
  lint: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
