name: solviolin_admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.8+10

environment:
  sdk: ^3.5.2
  flutter: 3.24.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.4
  flutter_secure_storage: ^4.2.1
  flutter_slidable: ^0.6.0
  get: ^4.6.1
  google_fonts: ^2.3.1
  intl: ^0.19.0
  path_provider: ^2.0.9
  pretty_dio_logger: ^1.1.1
  qr_code_scanner: ^0.6.1
  syncfusion_flutter_calendar: ^24.1.46
  syncfusion_flutter_xlsio: ^24.1.46
  cupertino_icons: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
