name: secrets

on: workflow_dispatch

jobs:
  extract-student:
    environment: solviolin
    runs-on: self-hosted

    steps:
      - run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ./solviolin/android/app/key.jks
          echo storeFile=./key.jks > ./solviolin/android/key.properties
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ./solviolin/android/key.properties
          echo storePassword=\${{ secrets.PASSWORD }} >> ./solviolin/android/key.properties
          echo keyPassword=\${{ secrets.PASSWORD }} >> ./solviolin/android/key.properties

  extract-admin:
    environment: solviolin-admin
    runs-on: self-hosted

    steps:
      - run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ./solviolin-admin/android/app/key.jks
          echo storeFile=./key.jks > ./solviolin-admin/android/key.properties
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ./solviolin-admin/android/key.properties
          echo storePassword=\${{ secrets.PASSWORD }} >> ./solviolin-admin/android/key.properties
          echo keyPassword=\${{ secrets.PASSWORD }} >> ./solviolin-admin/android/key.properties
